- hosts: localhost
  tasks:
  - name: download file
    get_url:
      url: http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pem
      dest: /tmp/a.conf
      mode: '400'
      
