- name: Copy Public key
  get_url:
    url:  http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
    dest: /tmp/openstack.pub
    mode: 0440
    
- name: Create OSP keypair
  os_keypair:
    cloud: ospcloud
    state: present
    name: ansible_ssh
    public_key_file:  "/tmp/openstack.pub"
    # public_key_file: "{{ ansible_env.HOME }}/.ssh/test_id_rsa.pub"
